### PR TITLE
Remove double quotes from cooke value

### LINKED ISSUE #2207: Some cookies have quotes around them
I've seen that some cookies, accessed by `request.headers.cookie["cookie-key"]?.string` have quote characters at the beginning and end. I believe they happen when the cookie itself contains a special character like / or +.

I believe Vapor should automatically trim those quote characters out of the value. They are just a detail of how the cookie is encoded.

[This is where that trimming happens in Kitura](https://github.com/IBM-Swift/Kitura/blob/ac4d947b701635cc5eba2de7fd1b25f3be6dbef4/Sources/Kitura/RouterRequest.swift#L331)

### Steps to reproduce

Try setting a cookie value like `+cookie/value`

Get that cookie from Vapor. It is returned as `"+cookie/value"`

### Expected behavior

It should be returned as `+cookie/value`

### Environment

* Vapor Framework version: 4.0.0-beta.4.2

### PR DESCRIPTION
**Pull request by tanner0101**
Automatically removes double-quotes from HTTP cookie values after trimming whitespace (#2215, fixes #2207).

### CODE REVIEW

File: Sources/Vapor/HTTP/HTTPCookies.swift [hunk 1]
```diff
@@ -308,3 +310,21 @@ public struct HTTPCookies: ExpressibleByDictionaryLiteral {
         set { cookies[name] = newValue }
     }
 }
+
+
+private extension String {
+    func removingDoubleQuotes() -> Self {
+        switch (self.first, self.last) {
+        case (Character.doubleQuote, Character.doubleQuote):
```
Comment (bridger) [inline Sources/Vapor/HTTP/HTTPCookies.swift]: giphy-2

**Comment by tanner0101** [comment]
These changes are now available in [4.0.0-rc.3.2](https://github.com/vapor/vapor/releases/tag/4.0.0-rc.3.2)
