### PR TITLE
Fix flaky Websocket tests

### LINKED ISSUE #2610: promise leak in WebSocketTests
Just ran the vapor tests and they did in fact all pass. However, I still got a crash in the end because the promise at `leaking promise created at (file: "/private/tmp/.nio-release-tools_jFGvKd/vapor/Tests/VaporTests/WebSocketTests.swift", line: 10)` seems to have leaked. This is `Xcode 12.4` on macOS. Run with `swift test --sanitize=address --enable-test-discovery`.

I don't think it matters if this is run with or without `--sanitize=address` but it may affect timing.

```
Test Case '-[VaporTests.ValidationTests testValidateNestedEachIndex]' passed (0.003 seconds).
Test Suite 'ValidationTests' passed at 2021-04-26 4:16:23.187 pm.
	 Executed 21 tests, with 0 failures (0 unexpected) in 0.049 (0.050) seconds
Test Suite 'ViewTests' started at 2021-04-26 4:16:23.187 pm
Test Case '-[VaporTests.ViewTests testViewResponse]' started.
adding 1 to http_requests_total
recording 2049707 http_request_duration_seconds
[ INFO ] GET /view [request-id: 6F3FFD10-503F-4246-AABD-3AF10F797F7D]
Test Case '-[VaporTests.ViewTests testViewResponse]' passed (0.007 seconds).
Test Suite 'ViewTests' passed at 2021-04-26 4:16:23.194 pm.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.007 (0.007) seconds
Test Suite 'WebSocketTests' started at 2021-04-26 4:16:23.194 pm
Test Case '-[VaporTests.WebSocketTests testLifecycleShutdown]' started.
adding 1 to http_requests_total
recording 698059 http_request_duration_seconds
[ NOTICE ] Server starting on http://127.0.0.1:1337
[ INFO ] GET /watcher [request-id: 4F79854F-3750-4B93-AFDC-D978B61ABFBA]
Test Case '-[VaporTests.WebSocketTests testLifecycleShutdown]' passed (0.051 seconds).
Test Case '-[VaporTests.WebSocketTests testManualUpgradeToWebSocket]' started.
adding 1 to http_requests_total
recording 495770 http_request_duration_seconds
[ NOTICE ] Server starting on http://127.0.0.1:8080
[ INFO ] GET /foo [request-id: 9C74F200-D2D2-46D9-9FD7-34635F121AFB]
Test Case '-[VaporTests.WebSocketTests testManualUpgradeToWebSocket]' passed (0.014 seconds).
Test Case '-[VaporTests.WebSocketTests testWebSocket404]' started.
adding 1 to http_requests_total
recording 389371 http_request_duration_seconds
[ NOTICE ] Server starting on http://127.0.0.1:8085
[ INFO ] GET /foo [request-id: 9D26A845-C9E3-4A49-8B28-2E0094D69B65]
Test Case '-[VaporTests.WebSocketTests testWebSocket404]' passed (0.013 seconds).
Test Case '-[VaporTests.WebSocketTests testWebSocketClient]' started.
adding 1 to http_requests_total
recording 488635 http_request_duration_seconds
[ INFO ] GET /ws [request-id: EA613DC8-D8AD-4802-A81D-AECB2C6D21E1]
[ WARNING ] read(descriptor:pointer:size:): Connection reset by peer (errno: 54) [request-id: EA613DC8-D8AD-4802-A81D-AECB2C6D21E1]
Fatal error: leaking promise created at (file: "/private/tmp/.nio-release-tools_jFGvKd/vapor/Tests/VaporTests/WebSocketTests.swift", line: 10): file /private/tmp/.nio-release-tools_jFGvKd/vapor/Tests/VaporTests/WebSocketTests.swift, line 10
Exited with signal code 4
```

### LINKED ISSUE #2618: WebSocketTests.testWebSocketClient test failure - incorrect server response
Log attached with full details of the failure:
>Test Case 'WebSocketTests.testWebSocketClient' started at 2021-05-06 15:35:09.572
[ INFO ] GET /ws [request-id: 4E8ECBAD-5745-4E92-B0B0-C8AAFFC0A155]
[ WARNING ] read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [request-id: 4E8ECBAD-5745-4E92-B0B0-C8AAFFC0A155]
adding 1 to http_requests_total
adding 1 to http_request_errors_total
recording 601669829119 http_request_duration_seconds
/workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/Tests/VaporTests/WebSocketTests.swift:26: error: WebSocketTests.testWebSocketClient : XCTAssertEqual failed: ("internalServerError") is not equal to ("ok") - 
Fatal error: leaking promise created at (file: "/workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/Tests/VaporTests/WebSocketTests.swift", line: 10): file /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/Tests/VaporTests/WebSocketTests.swift, line 10
Current stack trace:
/workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/Tests/VaporTests/WebSocketTests.swift:27: error: WebSocketTests.testWebSocketClient : XCTAssertEqual failed: ("{"error":true,"reason":"read(descriptor:pointer:size:): Connection reset by peer (errno: 104)"}") is not equal to ("Hello, world!") - 
0    libswiftCore.so                    0x00007f4b366b7db0 swift_reportError + 50
1    libswiftCore.so                    0x00007f4b36729f60 _swift_stdlib_reportFatalErrorInFile + 115
2    libswiftCore.so                    0x00007f4b3643edfe <unavailable> + 1383934
3    libswiftCore.so                    0x00007f4b3643ea07 <unavailable> + 1382919
4    libswiftCore.so                    0x00007f4b3643efe8 <unavailable> + 1384424
5    libswiftCore.so                    0x00007f4b3643d2d0 _assertionFailure(_:_:file:line:flags:) + 520
6    vaporPackageTests.xctest           0x0000556d7e5c99c5 <unavailable> + 7109061
7    vaporPackageTests.xctest           0x0000556d7e6b16ae <unavailable> + 8058542
8    vaporPackageTests.xctest           0x0000556d7e6b1618 <unavailable> + 8058392
9    vaporPackageTests.xctest           0x0000556d7e5c93e4 <unavailable> + 7107556
10   vaporPackageTests.xctest           0x0000556d7e5c9bf5 <unavailable> + 7109621
11   libswiftCore.so                    0x00007f4b366b9d1b <unavailable> + 3984667
12   vaporPackageTests.xctest           0x0000556d7ed005f5 <unavailable> + 14673397
13   libswiftCore.so                    0x00007f4b366b9d1b <unavailable> + 3984667
14   vaporPackageTests.xctest           0x0000556d7e9a32a0 <unavailable> + 11145888
15   vaporPackageTests.xctest           0x0000556d7e9a3309 <unavailable> + 11145993
16   libswiftCore.so                    0x00007f4b366b9d1b <unavailable> + 3984667
17   libswiftCore.so                    0x00007f4b366b1210 swift_arrayDestroy + 59
18   libswiftCore.so                    0x00007f4b36460c90 _ContiguousArrayStorage.__deallocating_deinit + 39
0x556d7e0a5179, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install() -> () at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:67
0x556d7e0a5188, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install() -> () at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/<compiler-generated>:0
0x7f4b360e097f
0x7f4b3643d4e5
0x556d7e5c99c4, closure #1 () -> () in NIO.EventLoopFuture.deinit at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIO/EventLoopFuture.swift:423
0x556d7e6b16ad, closure #1 () -> Swift.Bool in implicit closure #1 () -> Swift.Bool in NIO.debugOnly(() -> ()) -> () at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIO/Utilities.swift:44
0x556d7e6b1617, NIO.debugOnly(() -> ()) -> () at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIO/Utilities.swift:44
0x556d7e5c93e3, NIO.EventLoopFuture.deinit at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIO/EventLoopFuture.swift:419
0x556d7e5c9bf4, NIO.EventLoopFuture.__deallocating_deinit at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIO/EventLoopFuture.swift:0
0x7f4b366b9d1a
0x556d7ed005f4, objectdestroy.5 at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/vapor/<compiler-generated>:0
0x7f4b366b9d1a
0x556d7e9a329f, NIOWebSocket.NIOWebSocketClientUpgrader.deinit at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift:0
0x556d7e9a3308, NIOWebSocket.NIOWebSocketClientUpgrader.__deallocating_deinit at /workspace/.logs/**/*.log/00FB59CB-317C-4766-AF95-65F01B2A86C5/repos/swift-nio/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift:0
0x7f4b366b9d1a
0x7f4b366b124a
0x7f4b36460cb6

### LINKED ISSUE #2669: Crashing test `testWebSocketClient`
The test case `[VaporTests.WebSocketTests testWebSocketClient]` crashes, if the external service "echo.websocket.org", does not return a valid websocket response.

```swift
    func testWebSocketClient() throws {
        let app = Application(.testing)
        defer { app.shutdown() }

        app.get("ws") { req -> EventLoopFuture<String> in
            let promise = req.eventLoop.makePromise(of: String.self) // <--- a leaking promise is created here, in case there is no connection
            return WebSocket.connect(
                to: "ws://echo.websocket.org/",
                on: req.eventLoop
            ) { ws in
                ws.send("Hello, world!")
                ws.onText { ws, text in
                    promise.succeed(text)
                    ws.close().cascadeFailure(to: promise)
                }
            }.flatMap {
                return promise.futureResult
            }
        }

        try app.testable().test(.GET, "/ws") { res in
            XCTAssertEqual(res.status, .ok)
            XCTAssertEqual(res.body.string, "Hello, world!")
        }
    }
```

### To Reproduce

- run test when "echo.websocket.org" is down, or your are not connected to the internet

### Fix

- [ ] don't leak promise on the unhappy path
- [ ] don't use external service that is only reachable on the public internet (always a source of flakyness)

### Environment

- darwin and linux

### Vapor

- main branch

### PR DESCRIPTION
**Pull request by 0xTim**
This PR fixes the flaky websocket tests by bringing it all in house.

The websocket server we were using failed frequently causing issues with testing and has now been shutdown. By running a local server we should fix these issues.

Resolves #2669 
Resolves #2618 
Resolves #2610

### CODE REVIEW

File: Tests/VaporTests/WebSocketTests.swift [hunk 1]
```diff
@@ -3,13 +3,26 @@ import XCTest
 
 final class WebSocketTests: XCTestCase {
     func testWebSocketClient() throws {
+        let server = Application(.testing)
+
+        server.http.server.configuration.port = 8086
```
Comment (fabianfett) [inline Tests/VaporTests/WebSocketTests.swift:8]: To make this potentially even less flaky, we could also use the automatic free port picking:
https://github.com/vapor/vapor/pull/2572/files

**Review by fabianfett — APPROVED** [review]
Great. Thanks! One suggestion...

File: Tests/VaporTests/WebSocketTests.swift (hunk 1 above)
Comment (0xTim) [reply Tests/VaporTests/WebSocketTests.swift]: Good point

File: Tests/VaporTests/WebSocketTests.swift [hunk 2]
```diff
@@ -3,13 +3,32 @@ import XCTest
...
+            server.shutdown()
+        }
+
+        guard let localAddress = server.http.server.shared.localAddress,
+              let port = localAddress.port else {
+                  XCTFail("couldn't get port from \(app.http.server.shared.localAddress.debugDescription)")
+                  return
+              }
 
         app.get("ws") { req -> EventLoopFuture<String> in
```
Comment (fabianfett) [inline Tests/VaporTests/WebSocketTests.swift:28]: Oh, why is the call to the websocket triggered in an `HTTPRequest`. I would guess, if you really want to use the WebSocket client, you could drop the `app = Application(.testing)` and just use the `WebSocket.connect`

Comment (0xTim) [reply Tests/VaporTests/WebSocketTests.swift:28]: Honestly I'm not sure!

**Review by fabianfett — APPROVED** [review]
Awesome

**Review by Joannis — APPROVED** [review]
