### PR TITLE
Fix `content-length` calculation when streaming files

### LINKED ISSUE #2834: Safari loses connection when streaming `.mp4` files
### Describe the bug

When a route is configured to stream a `.mp4` file, this seems to be working on Chrome and Firefox. However in Safari, after a while, the video stops buffering due to failed HTTP Requests.

From what I've discovered, the Vapor application does send a response to the request, but Safari fails to recognise it as a proper request. This is most likely due to a `errno 32 - Broken pipe` being thrown somewhere in the stack.

### To Reproduce

1. To begin with, clone this repository for testing purposes:
`https://github.com/BennyDeBock/videoTest.git`
2. Fill in the path to the files in `routes.swift`
3. Run the application
4. Open `http://127.0.0.1:8080/` or `http://127.0.0.1:8080/hello` in Safari and play the video. After a while it should stop buffering

### Expected behavior

I expect the buffering to work with no issues without Safari telling me there are failed HTTP requests

### Environment

* Vapor Framework version: 4.60.1
* Vapor Toolbox version: 18.3.6
* OS version: 12.4

### Additional context
Other issues i've come across when debugging are:
- errno 54 - connection reset by peer
- error notEnoughBytes
- unhandled user event - outputClosed

### PR DESCRIPTION
**Pull request by BennyDeBock**
Fix the byte count calculation in `FileIO` when handling a range.

Resolves #2834

### CODE REVIEW

File: Tests/VaporTests/FileTests.swift [hunk 1]
```diff
@@ -63,6 +63,102 @@ final class FileTests: XCTestCase {
         }
     }
     
+//    func testStreamFileContentHeaderTail() throws {
```
Comment (0xTim) [inline Tests/VaporTests/FileTests.swift:66]: Leaving in for #2836

**Review by 0xTim — APPROVED** [review]
