### PR TITLE
Fix invalid session ID handling

### LINKED ISSUE #2339: Problem persisting session data to database
I'm having problems persisting my session data in a MySQL database.

### Steps to reproduce

When I use this in configure.swift:

```
app.sessions.use( .fluent( .mysql ) )
app.middleware.use( app.sessions.middleware )
app.migrations.add( SessionRecord.migration )
```

it doesn't work. It only works when `app.sessions.use( .memory )` is used. But then the in-memory storage is used. By the way, the migration works and the tables are created in the database.

### Expected behavior

Session data should get stored in the database table when for example this `request.session.data[ "userID" ] = loginResponse.id.uuidString` is used.

### Actual behavior

Nothing happens. Nothing is saved to the database table and no error is reported.

### Fix

Browser cookies had to be cleared. Then it started storing the data in the database.

### Environment

* Vapor Framework version: 4
* Vapor Toolbox version: 3.1.10
* OS version: macOS

### PR DESCRIPTION
**Pull request by tanner0101**
Requests containing unrecognized session IDs will now result in a new session being created (#2347, fixes #2339). 

This fixes a problem where clearing browser cookies would be required after changing Vapor's session driver.

### CODE REVIEW

**Comment by tanner0101** [comment]
Previously `SessionMiddleware` would treat unrecognized session identifiers as valid sessions with empty data. This would result in a session update query instead of create when sending the response. Session update on invalid identifiers is undefined behavior. Now, if a session identifier is not recognized, the invalid identifier is discarded and a new session with a new identifier is created. This means passing an invalid identifier has the same behavior as passing no identifier at all. I think this makes more sense than throwing an error since session identifiers can become invalid or expire normally.

File: Sources/Vapor/Sessions/SessionsMiddleware.swift [hunk 1]
```diff
@@ -42,7 +42,13 @@ public final class SessionsMiddleware: Middleware {
...
             let id = SessionID(string: cookieValue.string)
             return self.session.readSession(id, for: request).flatMap { data in
-                request._sessionCache.session = .init(id: id, data: data ?? .init())
+                if let data = data {
+                    // Session found, restore data and id.
+                    request._sessionCache.session = .init(id: id, data: data)
+                } else {
+                    // Session id not found, create new session.
+                    request._sessionCache.session = .init()
+                }
```
Comment (tdotclare) [inline Sources/Vapor/Sessions/SessionsMiddleware.swift:51]: Looks good to me!

**Comment by tanner0101** [comment]
These changes are now available in [4.5.1](https://github.com/vapor/vapor/releases/tag/4.5.1)
