### PR TITLE
Retain cycle fixes

### LINKED ISSUE #1870: Threads not closed on `deinit` / `shutdownGracefully`
When creating a `testable` application for unit testing (got my example from the raywenderlich/vapor-til project) the threads spawned in the `BlockingIOThreadPool` aren't closed. The threadpool is closed in `Application.swift`'s `deinit` call, but that somehow doesn't get called when a `XCTestCase` finishes (force setting `app = nil` in `tearDown` freezes the whole thing when you have a DB connection open).

Never noticed it before, but after about 300+ unit tests `xctest` had around 750 threads open. After calling 
```swift
let threadPool = try app.make(BlockingIOThreadPool.self)
try threadPool.syncShutdownGracefully()
```
in the `tearDown` method, it opens up max. 20 threads with 300+ unit tests.

This seems like a memory leak, since `app` never get's deinitialized. Don't know if its a vapor issue, or a issue with the way i'm testing.

### Steps to reproduce
1. Setup empty project `vapor new UnitTestLeak && cd UnitTestLeak && vapor xcode`
2. Add a new route to `Sources/App/routes.swift` for more realistic testing
```swift
struct FooContent: Content {
    var foo = "Foo"
    var bar = "Bar"
}

router.get("foo") { req in
    return FooContent()
}
```
3. Change the contents of `Tests/AppTests/AppTests.swift` to:
```swift
@testable import App
import Vapor
import XCTest

/// Add Application+Testable extension, taken from https://github.com/raywenderlich/vapor-til/blob/master/Tests/AppTests/Application%2BTestable.swift
extension Application {
    static func testable(envArgs: [String]? = nil) throws -> Application {
        var config = Config.default()
        var services = Services.default()
        var env = Environment.testing
        
        if let environmentArgs = envArgs {
            env.arguments = environmentArgs
        }
        
        try App.configure(&config, &env, &services)
        let app = try Application(config: config, environment: env, services: services)
        
        try App.boot(app)
        return app
    }
    
    /// Simplified sendRequest from https://github.com/raywenderlich/vapor-til/blob/master/Tests/AppTests/Application%2BTestable.swift#L58
    func sendRequest<T>(to path: String,
                        method: HTTPMethod = .GET,
                        headers: HTTPHeaders = .init(),
                        body: T? = nil) throws -> Response where T: Content {
        let responder = try self.make(Responder.self)
        let request = HTTPRequest(method: method, url: URL(string: path)!, headers: headers)
        let wrappedRequest = Request(http: request, using: self)
        if let body = body {
            try wrappedRequest.content.encode(body)
        }
        return try responder.respond(to: wrappedRequest).wait()
    }
}

/// Same as in routes.swift (not exposed when defined in routes.swift, usually this would be an entity or something like that, that would be exposed in @testable import App)
struct FooContent: Content {
    var foo = "Foo"
    var bar = "Bar"
}

/// Basic AppTest Case
final class AppTests: XCTestCase {
    var app: Application!
    
    /// As per example in Vapor-Til, create a new App
    override func setUp() {
        super.setUp()
        
        app = try! Application.testable()
    }
    
    /// Shutdown the app gracefully
    override func tearDown() {
        try? app.syncShutdownGracefully() // with 30 tests leaves about 130 threads open
        
        super.tearDown()
    }
    
    private func foo() throws {
        // send a request to the /foo route created in routes.swift
        let response = try app.sendRequest(to: "/foo",
                                           method: .GET,
                                           headers: .init(),
                                           body: FooContent())
        // check if its 200
        XCTAssertEqual(response.http.status, HTTPStatus.ok)
        
        let foo = try response.content.syncDecode(FooContent.self)
        
        sleep(1) // otherwise it's way too fast to check the threadcount
        
        /// some asserts
        XCTAssertEqual(foo.foo, "Foo")
        XCTAssertEqual(foo.bar, "Bar")
    }
    
    /// Let's run this about 30 times
    func testFoo() throws { try foo() }
    func testFoo1() throws { try foo() }
    func testFoo2() throws { try foo() }
    func testFoo3() throws { try foo() }
    func testFoo4() throws { try foo() }
    func testFoo5() throws { try foo() }
    func testFoo6() throws { try foo() }
    func testFoo7() throws { try foo() }
    func testFoo8() throws { try foo() }
    func testFoo9() throws { try foo() }
    func testFoo10() throws { try foo() }
    func testFoo11() throws { try foo() }
    func testFoo12() throws { try foo() }
    func testFoo13() throws { try foo() }
    func testFoo14() throws { try foo() }
    func testFoo15() throws { try foo() }
    func testFoo16() throws { try foo() }
    func testFoo17() throws { try foo() }
    func testFoo18() throws { try foo() }
    func testFoo19() throws { try foo() }
    func testFoo20() throws { try foo() }
    func testFoo21() throws { try foo() }
    func testFoo22() throws { try foo() }
    func testFoo23() throws { try foo() }
    func testFoo24() throws { try foo() }
    func testFoo25() throws { try foo() }
    func testFoo26() throws { try foo() }
    func testFoo27() throws { try foo() }
    func testFoo28() throws { try foo() }
    func testFoo29() throws { try foo() }
    func testFoo30() throws { try foo() }

    static let allTests = [
        ("testFoo", testFoo),
        ("testFoo1", testFoo1),
        ("testFoo2", testFoo2),
        ("testFoo3", testFoo3),
        ("testFoo4", testFoo4),
        ("testFoo5", testFoo5),
        ("testFoo6", testFoo6),
        ("testFoo7", testFoo8),
        ("testFoo9", testFoo9),
        ("testFoo10", testFoo10),
        ("testFoo11", testFoo11),
        ("testFoo12", testFoo12),
        ("testFoo13", testFoo13),
        ("testFoo14", testFoo14),
        ("testFoo15", testFoo15),
        ("testFoo16", testFoo16),
        ("testFoo17", testFoo17),
        ("testFoo18", testFoo18),
        ("testFoo19", testFoo19),
        ("testFoo20", testFoo20),
        ("testFoo21", testFoo21),
        ("testFoo22", testFoo22),
        ("testFoo23", testFoo23),
        ("testFoo24", testFoo24),
        ("testFoo25", testFoo25),
        ("testFoo26", testFoo26),
        ("testFoo27", testFoo27),
        ("testFoo28", testFoo28),
        ("testFoo29", testFoo29),
        ("testFoo30", testFoo30),
    ]
}
```
4. Check the threads in Activity Monitor or something like that (profile/analyse + unit test doesn't work, right?)
5. Check with setting `app = nil` explicitly in `tearDown`
```swift
override func tearDown() {
    app = nil // with 30 tests leaves about 80 threads open, so better, but not great. Freezes when also opening PostgreSQL connection (conn = try! app.newConnection(to: .psql).wait())
    super.tearDown()
}
```
6. Check the threads once again, see the improvement, yet still not closing all threads

### Expected behavior

When calling `app.shutdownGracefully`/`app.syncShutdownGracefully`  all threads opened when creating / booting a new app should close. 

### Actual behavior

The threads don't close, so when a project has a lot of unit tests (started having problems on quad-core i7 after around 300 unit tests) it opens up 700+ threads, causing `xctest` to act weird (was hanging silently, no errors thrown)

### Environment

* Vapor Framework version: 3.1.0
* Vapor Toolbox version: 3.1.10
* OS version: Mac OS Mojave 10.14.1

### PR DESCRIPTION
**Pull request by MrLotU**
Fixes #1870 and other memory leak related issues.

### CODE REVIEW

File: Sources/Vapor/Client/Client.swift [hunk 1]
```diff
@@ -17,7 +17,7 @@ extension Container {
 ///
 public protocol Client {
     /// The `Container` to use for creating `Request`s.
-    var container: Container { get }
+    var container: Container! { get }
```
Comment (MrLotU) [inline Sources/Vapor/Client/Client.swift]: I personally reall (REALLY) dislike having to put the `!` here, but it was the only way I could think of not making everyone use optional-chaining everywhere, since it's required to make this `weak`

File: Sources/Vapor/Server/NIOServer.swift [hunk 2]
```diff
@@ -12,10 +12,7 @@ public final class NIOServer: Server, ServiceType {
     public let config: NIOServerConfig
 
     /// Container for setting on event loops.
-    public let container: Container
-
-    /// Hold the current worker. Used for deinit.
-    private var currentWorker: Worker?
```
Comment (MrLotU) [inline Sources/Vapor/Server/NIOServer.swift]: I removed `currentWorker` since:

1. It was not implemented
2. If it were implemented, it'd always point to `container` anyways (unless I missed something)

File: Sources/Vapor/Client/Client.swift (hunk 1 above)
Comment (0xTim) [reply Sources/Vapor/Client/Client.swift]: Couple of things - first this is a breaking change so would have to be a major version release. 2nd if this were to be implemented, and the Client implementation were to nil out the container (because the thing holding onto it strongly cleaned it up) if you then accessed it, it would crash 😞

Comment (tanner0101) [reply Sources/Vapor/Client/Client.swift]: We should be able to make this a `weak` var privately on the clients, and expose a computed property for accessing it without needing to change the protocol. 

Something like:

```swift
var container: Container { return self._container! }

private weak var _container: Container?
```

File: Sources/Vapor/Server/NIOServer.swift [hunk 3]
```diff
@@ -112,7 +109,7 @@ public final class NIOServer: Server, ServiceType {
 
     /// Called when the server deinitializes.
     deinit {
-        currentWorker?.shutdownGracefully {
+        container.shutdownGracefully {
```
Comment (tanner0101) [inline Sources/Vapor/Server/NIOServer.swift]: This should still call `currentWorker?.shutdownGracefully`. We just need to actually set `currentWorker` haha

File: Sources/Vapor/Server/NIOServer.swift [hunk 4]
```diff
@@ -22,6 +25,7 @@ public final class NIOServer: Server, ServiceType {
     public init(config: NIOServerConfig, container: Container) {
         self.config = config
         self.container = container
+        self.currentWorker = container
```
Comment (tanner0101) [inline Sources/Vapor/Server/NIOServer.swift]: This should be set to the event loop group created during boot.

https://github.com/vapor/vapor/blob/6c8c17557dd081c669a65031548a42da74072ab5/Sources/Vapor/Server/NIOServer.swift#L52

As long as the `Container` here (actually an Application) is not being held onto strongly, the application will deinit and shutdown its own ELG. The server is only responsible for not creating a reference cycle to application and shutting down the ELG that it creates.

Comment (MrLotU) [reply Sources/Vapor/Server/NIOServer.swift]: Ah! Will fix!

**Comment by MrLotU** [comment]
@tanner0101 I still don't feel 100% OK about the force unwrapping of the `Container` though... How certain are we that it'll never be `nil`?

**Comment by tanner0101** [comment]
If it's `nil`, that means the application has deinitialized. If you're still hanging onto a client at that point, I think it's fine to crash. Adding a `fatalError` there instead of just force unwrapping might be better at least. But we really don't have any better options :\

**Comment by MrLotU** [comment]
Made it a `fatalError` so we can give some insight as to why we're crashing

**Comment by MrLotU** [comment]
I have a test project created [here](https://github.com/MrLotU/Threads). If you set the `vapor` version to `.branch("master")` it'll be leaking threads like crazy, but if you switch to `.branch("MemTestFixes")` (this branch) that'll all be gone :)

You'll be able to see this by putting a breakpoint on [`super.tearDown()`](https://github.com/MrLotU/Threads/blob/master/Tests/AppTests/AppTests.swift#L70)

**Comment by MrLotU** [comment]
>We should be able to write a unit test by creating an application and holding a weak reference into something inside it (like `NIOServerConfig`?). If we start it up then shut it down and nil out the application, that weak reference should be nil

I’ll create one once I find a minute 😃

**Comment by MrLotU** [comment]
I validated the test by making the `Container` on `NIOServer` a non-weak property, and the test fails

**Comment by MrLotU** [comment]
@tanner0101 bump

**Comment by tanner0101** [comment]
Awesome, thanks a ton @MrLotU!

**Comment by penny-coin** [comment]
Hey @MrLotU, you just merged a pull request, have a coin! 

You now have 69 coins.
