### PR TITLE
Fix for #726

### LINKED ISSUE #726: Invalid app.json doesn't give understandable crash log
Cannot really create test for this, it would break it all....

Hi, I have discovered following issue

This is the buggy code: https://github.com/Tempo-Titans/titan-api/tree/fdbcee57775354cc1c9e824977ff194ef199a05f

Create `secrets/mysql.json` in `Config` then try to build it, you will get something like this:

```
fatal error: Error raised at top level: VaporMySQL.Provider.Error.noMySQLConfig: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.58.6/src/swift/stdlib/public/core/ErrorType.swift, line 184
2016-11-28 21:16:11.431758 App[24420:197232] fatal error: Error raised at top level: VaporMySQL.Provider.Error.noMySQLConfig: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.58.6/src/swift/stdlib/public/core/ErrorType.swift, line 184
Current stack trace:
0    libswiftCore.dylib                 0x0000000101085cc0 swift_reportError + 132
1    libswiftCore.dylib                 0x00000001010a2f50 _swift_stdlib_reportFatalErrorInFile + 112
2    libswiftCore.dylib                 0x0000000101051370 partial apply for (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 99
3    libswiftCore.dylib                 0x0000000100e990a0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
4    libswiftCore.dylib                 0x00000001010512b0 partial apply for (_assertionFailed(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
5    libswiftCore.dylib                 0x0000000100e995b0 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 124
6    libswiftCore.dylib                 0x0000000100ff5af0 partial apply for (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> Never).(closure #1) + 185
7    libswiftCore.dylib                 0x0000000100e990a0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
8    libswiftCore.dylib                 0x0000000100e98e80 _assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> Never + 144
9    libswiftCore.dylib                 0x0000000100ebc540 swift_unexpectedError_merged + 569
10   App                                0x0000000100003d50 main + 727
11   libdyld.dylib                      0x00007fffb88bb254 start + 1
```

This by it self doesn't make any sense because there is `mysql.json` config file in project!

So the reason why this app crashes is that there is a `,` missing in `app.json` config.
For some reason, it doesn't crashed on config validation but it crashes on db config, probably because when parsing of `app.json` dies it wont parse `mysql.json`.

This is fixed code:
https://github.com/Tempo-Titans/titan-api/tree/832249dcd548c933c1937324f6624f13d8128257

This is the diff you want to see.
https://github.com/Tempo-Titans/titan-api/commit/832249dcd548c933c1937324f6624f13d8128257

Thank you

### PR DESCRIPTION
**Pull request by syky27**
This PR depends on https://github.com/vapor/json/pull/19

### CODE REVIEW

**Comment by tannernelson** [comment]
What does this look like when printed to the console?

**Comment by syky27** [comment]
It looks like this:
```
Could not load configuration files: jsonError("/Users/syky/titans/titan-api/Config/app.json")
```
I am not sure how to get only that string...

File: Sources/Vapor/Droplet/Droplet.swift [hunk 1]
```diff
@@ -219,7 +219,7 @@ public class Droplet {
                     ]
                 )
             } catch {
```
Comment (tannernelson) [inline Sources/Vapor/Droplet/Droplet.swift]:
```swift
catch JSONError.parse(let path, let error) {
    log.error("Could not load configuration file at \(path). Check the syntax and try again.")
    log.verbose(error)
}

File: Sources/Settings/Config+Directory.swift [hunk 2]
```diff
@@ -2,6 +2,10 @@ import Core
 import Foundation
 import JSON
 
+private enum Error: Swift.Error {
```
Comment (tannernelson) [inline Sources/Settings/Config+Directory.swift]:
```swift
enum JSONError: Error {
    case parse(path: String, error: Error)
}
```

File: Sources/Vapor/Droplet/Droplet.swift (hunk 1 above)
Comment (syky27) [inline Sources/Vapor/Droplet/Droplet.swift]: I cannot pass `error` to `log.verbose()` because it  takes string.

I can do this: 
```
log.verbose("\(error.localizedDescription) \(error)")
```
 to get this 
```
The operation couldn’t be completed. (Jay.JayError error 3.) unexpectedCharacter(Jay.ByteReader)
```
To make it as verbose as possible.

The error object I am getting looks like this:
screenshot 2016-11-29 18 56 37


I could implement number of the character where parsing failed if you want. 
`cursor` is the number form beginning of the file.

**Comment by syky27** [comment]
@tannernelson I do not know what actually happened, but you somehow pushed all the PR that you merged to vapor to my fork as well.

Not quite sure if you wanted to, I don't mind because there are no conflicts.

This probably happened because I left the option *Allow edits from maintainers* turned on.

**Comment by syky27** [comment]
@tannernelson Ready for review

**Comment by tannernelson** [comment]
JSON 1.0.2 has been tagged.
https://github.com/vapor/json/releases/tag/1.0.2
