### PR TITLE
CORS: add "vary: origin" header if allowed origin is .originBased (#2539)

### LINKED ISSUE #2539: CORS "Vary: Origin" missing when allowed origin is .originBased
[This documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin) on CORS states the following when deriving the `Access-Control-Allow-Origin` value from the request's `Origin` header:

> To allow any site to make CORS requests without using the * wildcard (for example, to enable credentials), your server must read the value of the request's Origin header and use that value to set Access-Control-Allow-Origin, and must also set a Vary: Origin header to indicate that some headers are being set dynamically depending on the origin.

This is mentioned similarly on various other online resources about CORS headers.

The `CORSMiddleware` has an `AllowOriginSetting.originBased` which follows the above in setting the value for `Access-Control-Allow-Origin`, but it does not add the `Vary: Origin` header.

### To Reproduce

1. Use a `CORSMiddleware` with the `Configuration.default` configuration, which defaults the `AllowedOriginSetting` to `.originBased`.
2. Perform either a preflight request (`OPTIONS` with at least a `accessControlRequestMethod` request header) or a regular request with an `Origin` request header.
3. According to said documentation, the response should contain the `Vary` response header with value `Origin` (alongside the other CORS headers added by the `CORSMiddleware`), but it doesn't.

### Expected behavior

The request mentioned above under step 2 should yield a response _with_ the `Vary` response header with value `Origin`.

### Environment

* Vapor Framework version: 4.36.0
* Vapor Toolbox version: 3.1.10
* OS version: N/A

### PR DESCRIPTION
**Pull request by weissi**
- Set the "vary: origin" header when using the request's "origin" header. (fixes #2539).

> Note: Previously, the "Vary: Origin" header would not be set.

### CODE REVIEW

File: Tests/VaporTests/MiddlewareTests.swift [hunk 1]
```diff
@@ -29,4 +29,25 @@ final class MiddlewareTests: XCTestCase {
...
+        let app = Application(.testing)
+        defer { app.shutdown() }
+
+        app.grouped(
+            CORSMiddleware(configuration: .init(allowedOrigin: .originBased, allowedMethods: [.GET], allowedHeaders: [.origin]))
+        ).get("order") { req -> String in
+            return "done"
+        }
+
+        try app.testable().test(.GET, "/order", headers: ["Origin": "foo"]) { res in
```
Comment (0xTim) [inline Tests/VaporTests/MiddlewareTests.swift:43]: Small nit - this can be `app.test(...)` to clean it up a bit

```suggestion
        try app.test(.GET, "/order", headers: ["Origin": "foo"]) { res in
```

**Review by 0xTim — CHANGES_REQUESTED** [review]
Looks good overall, one small nit to keep things how I prefer them 😅 

If I'm being really picky, it would be good to have another test for CORS that sets the `AllowOriginSetting` to `.none` and ensure we don't set the origin header back

**Review by gwynne — CHANGES_REQUESTED** [review]
I know it's a bit pedantic of me, but can you also add a test that checks the negation? (e.g. that the header is _not_ added in at least one non-`.originBased` case?

**Comment by gwynne** [comment]
> I know it's a bit pedantic of me, but can you also add a test that checks the negation? (e.g. that the header is _not_ added in at least one non-`.originBased` case?)

Ah, I see Tim beat me to it :)

**Review by gwynne — APPROVED** [review]
Looks great! Thanks, @weissi!!

**Review by 0xTim — APPROVED** [review]
LGTM - last thing @weissi can you update the PR description as that becomes the release notes. Details [here](https://github.com/vapor/vapor/blob/master/.github/contributing.md#release-body)

**Comment by weissi** [comment]
@0xTim sure, better now?

**Comment by gwynne** [comment]
I love it.

**Comment by tanner0101** [comment]
These changes are now available in [4.39.1](https://github.com/vapor/vapor/releases/tag/4.39.1)
