### PR TITLE
Honor Configuration for Optional Date Decoding & Encoding

### LINKED ISSUE #2518: URLEncodedFormDecoders dateDecodingStrategy is ignored for optional dates.
URLEncodedFormDecoders dateDecodingStrategy is ignored for optional dates.

### Steps to reproduce

Configure a custom `URLEncodedFormDecoder` with `dateDecodingStrategy` `iso8601`:
```swift
let decoder = URLEncodedFormDecoder(configuration: .init(dateDecodingStrategy: .iso8601))
ContentConfiguration.global.use(urlDecoder: decoder)
```

Try to get a get an optional Date from a query
```swift
let after = try req.query.get(Date?.self, at: "after") ?? .distantPast
```

Make a request with a date in the expected format (e.g. "...?after=2020-10-28T10:31:14Z").

### Expected behavior

The date is parsed according to the configured decoder.

### Actual behavior

An error is thrown:
`[ ERROR ] Value of type 'Date' required for key 'after'.`

### Environment

* Vapor Framework version: 4.32.0
* Vapor Toolbox version: 18.2.2
* OS version: macOS Catalina 10.15.7

---

In `URLEncodedFormDecoder`, the following check fails, because type is "Swift.Optional<Foundation.Date>":
```swift
 func decode<T>(_ type: T.Type, forKey key: Key) throws -> T where T: Decodable {
       //Check if we received a date. We need the decode with the appropriate format
       guard !(T.self is Date.Type) else {
            return try decodeDate(forKey: key) as! T
       }
      ...
}
```

Therefore, the decoding continues in the `SingleValueContainer` which does not check if the type is `Date` and the default date-decoder is used.

### PR DESCRIPTION
**Pull request by andtie**
Honor the configuration for Date Decoding & Encoding in `URLEncodedFormDecoder` / `URLEncodedFormEncoder` (fixes #2518).

```swift
// Configure a non-default date decoding strategy
let decoder = URLEncodedFormDecoder(configuration: .init(dateDecodingStrategy: .iso8601))
ContentConfiguration.global.use(urlDecoder: decoder)

// allow to use optional date-parameters in a request 
let after = try req.query.get(Date?.self, at: "after") ?? .distantPast

// => dates with the expected format (e.g. "...?after=2020-10-28T10:31:14Z") are correctly parsed
```

### CODE REVIEW

File: Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift [hunk 1]
```diff
@@ -408,6 +384,10 @@ private struct _Decoder: Decoder {
         }
         
         func decode<T>(_ type: T.Type) throws -> T where T: Decodable {
+            //Check if we received a date. We need the decode with the appropriate format
```
Comment (siemensikkema) [inline Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift:387]:
```suggestion
            // Check if we received a date. We need the decode with the appropriate format.
```

**Review by siemensikkema — COMMENTED** [review]
Thanks for this PR! I wonder if the title and description correctly reflect the changes, though. The configuration was used before, it was just not applied to optional dates, correct?

**Comment by andtie** [comment]
Thanks for your reply!

> I wonder if the title and description correctly reflect the changes, though. The configuration was used before, it was just not applied to optional dates, correct?

Yes, you are correct. How about "Honor Configuration for Decoding & Encoding of optional Dates"? 
I am very open for suggestions.

File: Tests/VaporTests/URLEncodedFormTests.swift [hunk 2]
```diff
@@ -220,6 +220,21 @@ final class URLEncodedFormTests: XCTestCase {
         XCTAssertEqual(decodedCustom, toEncode)
     }
 
+    func testGH2518() throws {
```
Comment (0xTim) [inline Tests/VaporTests/URLEncodedFormTests.swift:223]: Small nit, can we rename this so it's clearer what the test achieves
```suggestion
    func testOptionalDateEncodingAndDecoding_GH2518() throws {
```

**Review by 0xTim — CHANGES_REQUESTED** [review]
One small nit on test name

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by tanner0101** [comment]
These changes are now available in [4.34.1](https://github.com/vapor/vapor/releases/tag/4.34.1)
