### PR TITLE
Fix misspelled property name of class Routes

### LINKED ISSUE #2426: spelling mistake - caseInsenstive
* Vapor Framework version: 4.14.0

`caseInsensitive` is misspelled as `caseInsenstive`

https://github.com/vapor/vapor/blob/9d57bde296912f3c66b78813e46b5535e1758aee/Sources/Vapor/Routing/Routes.swift#L8

### PR DESCRIPTION
**Pull request by wangyanxi**
Fix misspelled property name of class `Routes`, change from `caseInsenstive` to `caseInsensitive` (#2435, fixes #2426).

The misspelled `caseInsenstive` is now marked as deprecated.

### CODE REVIEW

File: Sources/Vapor/Routing/Routes.swift [hunk 1]
```diff
@@ -5,7 +5,17 @@ public final class Routes: RoutesBuilder, CustomStringConvertible {
     public var defaultMaxBodySize: ByteCount
     /// Default routing behavior of `DefaultResponder` is case-sensitive; configure to `true` prior to
     /// Application start handle `Constant` `PathComponents` in a case-insensitive manner.
-    public var caseInsenstive: Bool
+    public var caseInsensitive: Bool
+
+    @available(*, deprecated, renamed: "caseInsensitive")
```
Comment (tanner0101) [inline Sources/Vapor/Routing/Routes.swift:10]: Can you put this in the `Sources/Vapor/Deprecations/` folder?

Comment (wangyanxi) [reply Sources/Vapor/Routing/Routes.swift]: code changed. but some of checks failed, I don't known why 
Could you help check what went wrong?

File: Sources/Vapor/Deprecations/Routes+caseInsenstive.swift [hunk 2]
```diff
@@ -0,0 +1,20 @@
+//
+//  Routes+caseInsenstive.swift
+//  
+//
+//  Created by Yanxi on 2020/7/16.
+//
+
+extension Routes {
+
```
Comment (tanner0101) [inline Sources/Vapor/Deprecations/Routes+caseInsenstive.swift:9]: rm space

Comment (wangyanxi) [reply Sources/Vapor/Deprecations/Routes+caseInsenstive.swift]: removed

**Comment by tanner0101** [comment]
These changes are now available in [4.25.0](https://github.com/vapor/vapor/releases/tag/4.25.0)
